services:
  app:
    build:
      context: ../../
      dockerfile: deploy/flask_asgi_nginx/Dockerfile
    restart: unless-stopped

  nginx:
    image: nginx:1.27
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

